We have 2 different heroku deploys now
The origins are at heroku1 and heroku2
We switch between them using the new herotate utility script
We scale each worker up and down via the scale script

diff --git a/bin/deploy b/bin/deploy
--- a/bin/deploy
+++ b/bin/deploy
@@ -14,8 +14,8 @@ if ! [ -r "${HOME}/.local/share/heroku/config.json" ]; then
     exit 0
 fi
 
-git push heroku main || {
-    printf -- 'Unable to push to heroku.\n'
+git push "heroku${1}" main || {
+    printf -- 'Unable to push to heroku%s.\n' "$1"
 
     # Exit 0 so yarn doesn't complain
     exit 0
